# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag.proto

require 'google/protobuf'

require 'grpc/v2/common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tag.proto", :syntax => :proto3) do
    add_message "grpc.v2.tag_pb.GetTagListRequest" do
      optional :name, :string, 1
      optional :state, :uint32, 2
    end
    add_message "grpc.v2.tag_pb.Tag" do
      optional :id, :int64, 1
      optional :name, :string, 2
      optional :state, :uint32, 3
    end
    add_message "grpc.v2.tag_pb.GetTagListReply" do
      repeated :list, :message, 1, "grpc.v2.tag_pb.Tag"
      optional :pager, :message, 2, "grpc.v2.common_pb.Pager"
    end
  end
end

module Grpc
  module V2
    module TagPb
      GetTagListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.v2.tag_pb.GetTagListRequest").msgclass
      Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.v2.tag_pb.Tag").msgclass
      GetTagListReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.v2.tag_pb.GetTagListReply").msgclass
    end
  end
end
