# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tag.proto for package 'grpc.v2.tag_pb'

require 'grpc'
require 'grpc/v2/tag_pb'

module Grpc
  module V2
    module TagPb
      module TagService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'grpc.v2.tag_pb.TagService'

          rpc :GetTagList, ::Grpc::V2::TagPb::GetTagListRequest, ::Grpc::V2::TagPb::GetTagListReply
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
