# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag.proto

require 'google/protobuf'
# 生成的为 require 'common_pb'
# require 本质必须加载绝对路径，或者把路径拼接到全局变量 $LOAD_PATH 中, rails 中自动把 lib 加入到了 $LOAD_PATH 中，所以
# 上面这个路径无法识别，必须手动修改为 rails 可识别的路径
require 'grpc/v1/common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tag.proto", :syntax => :proto3) do
    add_message "v1.tag_pb.GetTagListRequest" do
      optional :name, :string, 1
      optional :state, :uint32, 2
    end
    add_message "v1.tag_pb.Tag" do
      optional :id, :int64, 1
      optional :name, :string, 2
      optional :state, :uint32, 3
    end
    add_message "v1.tag_pb.GetTagListReply" do
      repeated :list, :message, 1, "v1.tag_pb.Tag"
      optional :pager, :message, 2, "v1.common_pb.Pager"
    end
  end
end

module V1
  module TagPb
    GetTagListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.tag_pb.GetTagListRequest").msgclass
    Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.tag_pb.Tag").msgclass
    GetTagListReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.tag_pb.GetTagListReply").msgclass
  end
end
