default: &default
  adapter: <%= ENV["DB_ADAPTER"] %>
  port: <%= ENV["DB_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  charset: <%= ENV["DB_CHARSET"] %>
  reconnect: true
  collation: <%= ENV["DB_COLLATION"] %>
  max_connections: <%= ENV["DB_MAX_CONNECTIONS"] %>
  preconnect: "concurrently"
  database: <%= ENV["DB_NAME"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  encoding: utf8mb4

development:
  <<: *default
  database: <%= ENV["DEVELOPMENT_DB_NAME"] %>
  host: <%= ENV["DEVELOPMENT_DB_HOST"] %>
  username: <%= ENV["DEVELOPMENT_DB_USER"] %>
  password: <%= ENV["DEVELOPMENT_DB_PASSWORD"] %>
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: <%= ENV["TEST_DB_NAME"] %>
  host: <%= ENV["TEST_DB_HOST"] %>
  username: <%= ENV["TEST_DB_USER"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>