default:      &default
  adapter:    <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  url:        <%= ENV['PG_DATABASE_URL'] %>
  schema_search_path: "public,shared_extensions"
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool:       <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:    5000

development:
  <<:         *default
production:
  <<:         *default
test:
  <<:         *default
  url:        <%= ENV['TEST_DATABASE_URL'] || ENV['PG_DATABASE_URL'] %>