# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tag.proto for package 'k1.tag_pb'

require 'grpc'
require 'k1/tag_pb'

module K1
  module TagPb
    module TagService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'k1.tag_pb.TagService'

        rpc :GetTagList, ::K1::TagPb::GetTagListRequest, ::K1::TagPb::GetTagListReply
      end

      Stub = Service.rpc_stub_class
    end
  end
end
